version: "3.7"

services:

  clickhouse:
    image: clickhouse/clickhouse-server:23.3
    restart: unless-stopped
    ports:
      - 9000:9000
      - 8123:8123
    volumes:
      - "./clickhouse-data:/var/lib/clickhouse"
      - "./ckconfig/dns_dictionary.xml:/etc/clickhouse-server/dns_dictionary.xml"
      - "./ckconfig/dictionaries/:/opt/dictionaries/"
      - "./tables.sql:/docker-entrypoint-initdb.d/tables.sql:ro"

  grafana:
    image: grafana/grafana:latest
    user: "0"
    restart: unless-stopped
    environment:
      - GF_INSTALL_PLUGINS=vertamedia-clickhouse-datasource
    volumes:
      - "./grafana/data:/var/lib/grafana"
    ports:
      - 3000:3000
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '8080:8080'
    volumes:
      - "./nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
      - ./nginx/log:/var/log/nginx/:rw
    environment:
      - "PROXY_PASS=clickhouse"
