{
 "title": "DNS Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "dsource",
    "label": "Data Source",
    "query": "vertamedia-clickhouse-datasource"
   }
  ]
 },
 "panels": [
  {
   "title": "Top Queried domains",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "database": "default",
     "dateColDataType": "DnsDate",
     "dateTimeColDataType": "t",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font> <font color=\"darkseagreen\">timestamp</font>, <font color=\"navajowhite\">groupArray</font>((Question, <font color=\"navajowhite\">count</font>)) <font color=\"darkorange\">FROM</font> (<font color=\"darkorange\">SELECT</font> <font color=\"darkcyan\">$timeSeries</font>  <font color=\"darkorange\">as</font> <font color=\"darkseagreen\">timestamp</font>, Question, <font color=\"navajowhite\">sum</font>(c) <font color=\"darkorange\">as</font> <font color=\"navajowhite\">count</font> <font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font> <font color=\"darkorange\">WHERE</font> <font color=\"darkcyan\">$timeFilter</font> <font color=\"yellow\">AND</font> Server <font color=\"darkorange\">IN</font>(<font color=\"darkcyan\">$ServerName</font>) <font color=\"darkorange\">group by</font> t, Question <font color=\"darkorange\">ORDER BY</font> <font color=\"navajowhite\">count</font> <font color=\"darkorange\">desc</font> <font color=\"darkorange\">limit</font> <font color=\"cornflowerblue\">5</font> by <font color=\"darkseagreen\">timestamp</font>) <font color=\"darkorange\">group by</font> <font color=\"darkseagreen\">timestamp</font><br /> <font color=\"darkorange\">order by</font> <font color=\"darkseagreen\">timestamp</font>",
     "query": "SELECT timestamp, groupArray((Question, count)) FROM (SELECT $timeSeries  as timestamp, Question, sum(c) as count FROM DNS_DOMAIN_COUNT WHERE $timeFilter  group by t, Question ORDER BY count desc limit 5 by timestamp) GROUP BY timestamp ORDER BY timestamp",
     "rawQuery": "SELECT timestamp, groupArray((Question, count)) FROM (SELECT (intDiv(toUInt32(\"t\"), 1) * 1) * 1000  as timestamp, Question, sum(c) as count FROM DNS_DOMAIN_COUNT WHERE DnsDate >= toDate(1698114453) AND DnsDate <= toDate(1698115353) AND \"t\" >= toDateTime(1698114453) AND \"t\" <= toDateTime(1698115353)  group by t, Question ORDER BY count desc limit 5 by timestamp) GROUP BY timestamp ORDER BY timestamp",
     "round": "0s",
     "table": "DNS_DOMAIN_COUNT",
     "targetLists": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Unique Domains Queried Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "default",
     "dateColDataType": "DnsDate",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font> <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t, uniqMerge(UniqueDnsCount)<font color=\"yellow\">/</font><font color=\"darkcyan\">$interval</font> <font color=\"darkorange\">as</font> Count  <font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font> <font color=\"darkorange\">WHERE</font> <font color=\"darkcyan\">$timeFilter</font> <font color=\"yellow\">AND</font> Server <font color=\"darkorange\">IN</font>(<font color=\"darkcyan\">$ServerName</font>)   <font color=\"darkorange\">GROUP BY</font> t <font color=\"darkorange\">ORDER BY</font> t",
     "query": "SELECT $timeSeries as t, uniqMerge(UniqueDnsCount)/$interval as Count  FROM DNS_DOMAIN_UNIQUE WHERE $timeFilter    GROUP BY t ORDER BY t",
     "rawQuery": "SELECT (intDiv(toUInt32(timestamp), 1) * 1) * 1000 as t, uniqMerge(UniqueDnsCount)/1 as Count  FROM DNS_DOMAIN_UNIQUE WHERE DnsDate >= toDate(1698114602) AND DnsDate <= toDate(1698115502) AND timestamp >= toDateTime(1698114602) AND timestamp <= toDateTime(1698115502)    GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "DNS_DOMAIN_UNIQUE",
     "targetLists": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Packet Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "database": "default",
     "dateColDataType": "DnsDate",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font> <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t, avgMerge(AverageSize) <font color=\"darkorange\">AS</font> Bytes <font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font> <font color=\"darkorange\">WHERE</font> <font color=\"darkcyan\">$timeFilter</font> <font color=\"yellow\">AND</font> Server <font color=\"darkorange\">IN</font>(<font color=\"darkcyan\">$ServerName</font>)   <font color=\"darkorange\">Group by</font> t <font color=\"darkorange\">order by</font> t",
     "query": "SELECT $timeSeries as t, avgMerge(AverageSize) AS Bytes FROM DNS_GENERAL_AGGREGATIONS WHERE $timeFilter    Group by t order by t",
     "rawQuery": "SELECT (intDiv(toUInt32(timestamp), 1) * 1) * 1000 as t, avgMerge(AverageSize) AS Bytes FROM DNS_GENERAL_AGGREGATIONS WHERE DnsDate >= toDate(1698114669) AND DnsDate <= toDate(1698115569) AND timestamp >= toDateTime(1698114669) AND timestamp <= toDateTime(1698115569)    Group by t order by t",
     "round": "0s",
     "table": "DNS_GENERAL_AGGREGATIONS",
     "targetLists": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Packet Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "database": "default",
     "dateColDataType": "DnsDate",
     "dateTimeColDataType": "timestamp",
     "formattedQuery": "SELECT $timeSeries as t, sumMerge(TotalSize)*8/$interval as \"Bytes/s\" FROM $table   WHERE $timeFilter    Group by t order by t",
     "query": "SELECT $timeSeries as t, sumMerge(TotalSize)*8/$interval as \"Bytes/s\" FROM DNS_GENERAL_AGGREGATIONS WHERE $timeFilter    Group by t order by t",
     "table": "DNS_GENERAL_AGGREGATIONS",
     "targetLists": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Packet Count byIP Version",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "database": "default",
     "dateColDataType": "DnsDate",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font> t, <font color=\"navajowhite\">groupArray</font>((IPVersion, <font color=\"navajowhite\">count</font><font color=\"yellow\">/</font><font color=\"darkcyan\">$interval</font>)) <font color=\"darkorange\">FROM</font> (<font color=\"darkorange\">SELECT</font> <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t, IPVersion, <font color=\"navajowhite\">sum</font>(c) <font color=\"darkorange\">as</font> <font color=\"navajowhite\">count</font> <font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font> <font color=\"darkorange\">WHERE</font> <font color=\"darkcyan\">$timeFilter</font> <font color=\"yellow\">AND</font> Server <font color=\"darkorange\">IN</font>(<font color=\"darkcyan\">$ServerName</font>)   <font color=\"darkorange\">group by</font> t, IPVersion <font color=\"darkorange\">ORDER BY</font> t) <font color=\"darkorange\">group by</font> t<br /> <font color=\"darkorange\">order by</font> t",
     "query": "SELECT t, groupArray((IPVersion, count/$interval)) FROM (SELECT $timeSeries as t, IPVersion, sum(c) as count FROM DNS_SRCIP_MASK WHERE $timeFilter    group by t, IPVersion ORDER BY t) group by t\n order by t",
     "rawQuery": "SELECT t, groupArray((IPVersion, count/1)) FROM (SELECT (intDiv(toUInt32(timestamp), 1) * 1) * 1000 as t, IPVersion, sum(c) as count FROM DNS_SRCIP_MASK WHERE DnsDate >= toDate(1698114741) AND DnsDate <= toDate(1698115641) AND timestamp >= toDateTime(1698114741) AND timestamp <= toDateTime(1698115641)    group by t, IPVersion ORDER BY t) group by t\n order by t",
     "round": "0s",
     "table": "DNS_SRCIP_MASK",
     "targetLists": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Packet Count by Transport Protocol",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "database": "default",
     "dateColDataType": "DnsDate",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font> t, <font color=\"navajowhite\">groupArray</font>((Protocol, <font color=\"navajowhite\">count</font><font color=\"yellow\">/</font><font color=\"darkcyan\">$interval</font>)) <font color=\"darkorange\">FROM</font> (<font color=\"darkorange\">SELECT</font> <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t, Protocol, <font color=\"navajowhite\">sum</font>(c) <font color=\"darkorange\">as</font> <font color=\"navajowhite\">count</font> <font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font> <font color=\"darkorange\">WHERE</font> <font color=\"darkcyan\">$timeFilter</font> <font color=\"yellow\">AND</font> Server <font color=\"darkorange\">IN</font>(<font color=\"darkcyan\">$ServerName</font>)   <font color=\"darkorange\">group by</font> t, Protocol <font color=\"darkorange\">ORDER BY</font> t) <font color=\"darkorange\">group by</font> t<br /> <font color=\"darkorange\">order by</font> t",
     "query": "SELECT t, groupArray((Protocol, count/$interval)) FROM (SELECT $timeSeries as t, Protocol, sum(c) as count FROM DNS_PROTOCOL WHERE $timeFilter    group by t, Protocol ORDER BY t) group by t\n order by t",
     "rawQuery": "SELECT t, groupArray((Protocol, count/1)) FROM (SELECT (intDiv(toUInt32(timestamp), 1) * 1) * 1000 as t, Protocol, sum(c) as count FROM DNS_PROTOCOL WHERE DnsDate >= toDate(1698114794) AND DnsDate <= toDate(1698115694) AND timestamp >= toDateTime(1698114794) AND timestamp <= toDateTime(1698115694)    group by t, Protocol ORDER BY t) group by t\n order by t",
     "round": "0s",
     "table": "DNS_PROTOCOL",
     "targetLists": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "IPv4 Packet Destination Prefix",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "DnsDate",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT 0, groupArray((IP, total)) FROM (SELECT IPv6NumToString(SrcIP) AS IP,sum(c) as total FROM DNS_SRCIP_MASK PREWHERE IPVersion=4 WHERE $timeFilter      GROUP BY SrcIP order by SrcIP desc limit 20)",
     "rawQuery": "SELECT 0, groupArray((IP, total)) FROM (SELECT IPv6NumToString(SrcIP) AS IP,sum(c) as total FROM DNS_SRCIP_MASK PREWHERE IPVersion=4 WHERE DnsDate >= toDate(1698115058) AND DnsDate <= toDate(1698115958) AND timestamp >= toDateTime(1698115058) AND timestamp <= toDateTime(1698115958)      GROUP BY SrcIP order by SrcIP desc limit 20)",
     "round": "0s",
     "table": "DNS_SRCIP_MASK"
    }
   ]
  },
  {
   "title": "IPv6 Packet Destination Top 20 Prefix",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "DnsDate",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font> <font color=\"cornflowerblue\">0</font>, <font color=\"navajowhite\">groupArray</font>((IP, total)) <font color=\"darkorange\">FROM</font> (<font color=\"darkorange\">SELECT</font> <font color=\"navajowhite\">IPv6NumToString</font>(<font color=\"navajowhite\">toFixedString</font>(<font color=\"navajowhite\">unhex</font>(<font color=\"navajowhite\">hex</font>(SrcIP)), <font color=\"cornflowerblue\">16</font>)) <font color=\"darkorange\">AS</font> IP,<br /><font color=\"navajowhite\">sum</font>(c) <font color=\"darkorange\">as</font> total <font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font> <font color=\"darkorange\">PREWHERE</font> IPVersion<font color=\"yellow\">=</font><font color=\"cornflowerblue\">6</font> <font color=\"darkorange\">WHERE</font> <font color=\"darkcyan\">$timeFilter</font> <font color=\"yellow\">AND</font> Server <font color=\"darkorange\">IN</font>(<font color=\"darkcyan\">$ServerName</font>)    <font color=\"darkorange\">GROUP BY</font> SrcIP <font color=\"darkorange\">order by</font> SrcIP <font color=\"darkorange\">desc</font> <font color=\"darkorange\">limit</font> <font color=\"cornflowerblue\">20</font>)",
     "query": "SELECT 0, groupArray((IP, total)) FROM (SELECT IPv6NumToString(SrcIP) AS IP,sum(c) as total FROM DNS_SRCIP_MASK PREWHERE IPVersion=6 WHERE $timeFilter     GROUP BY SrcIP order by SrcIP desc limit 20)",
     "rawQuery": "SELECT 0, groupArray((IP, total)) FROM (SELECT IPv6NumToString(SrcIP) AS IP,sum(c) as total FROM DNS_SRCIP_MASK PREWHERE IPVersion=6 WHERE DnsDate >= toDate(1698115167) AND DnsDate <= toDate(1698116067) AND timestamp >= toDateTime(1698115167) AND timestamp <= toDateTime(1698116067)     GROUP BY SrcIP order by SrcIP desc limit 20)",
     "round": "0s",
     "table": "DNS_SRCIP_MASK",
     "targetLists": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DNS Question Type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "database": "default",
     "dateColDataType": "DnsDate",
     "dateTimeColDataType": "timestamp",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font> t, <font color=\"navajowhite\">groupArray</font>((<font color=\"navajowhite\">dictGetString</font>(<font color=\"lightgreen\">'dns_type'</font>, <font color=\"lightgreen\">'Name'</font>, <font color=\"navajowhite\">toUInt64</font>(<font color=\"darkorange\">Type</font>)), <font color=\"navajowhite\">count</font><font color=\"yellow\">/</font><font color=\"darkcyan\">$interval</font>)) <font color=\"darkorange\">FROM</font> (<font color=\"darkorange\">SELECT</font> <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t, <font color=\"darkorange\">Type</font>, <font color=\"navajowhite\">sum</font>(c) <font color=\"darkorange\">as</font> <font color=\"navajowhite\">count</font> <font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font> <font color=\"darkorange\">WHERE</font> <font color=\"darkcyan\">$timeFilter</font> <font color=\"yellow\">AND</font> Server <font color=\"darkorange\">IN</font>(<font color=\"darkcyan\">$ServerName</font>)   <font color=\"darkorange\">group by</font> t, <font color=\"darkorange\">Type</font> <font color=\"darkorange\">ORDER BY</font> t) <font color=\"darkorange\">group by</font> t<br /> <font color=\"darkorange\">order by</font> t",
     "query": "SELECT t, groupArray((dictGetString('dns_type', 'Name', toUInt64(Type)), count/$interval)) FROM (SELECT $timeSeries as t, Type, sum(c) as count FROM DNS_TYPE WHERE $timeFilter    group by t, Type ORDER BY t) group by t\n order by t",
     "table": "DNS_TYPE",
     "targetLists": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Query Class",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "database": "default",
     "dateColDataType": "DnsDate",
     "dateTimeColDataType": "timestamp",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font> t, <font color=\"navajowhite\">groupArray</font>((<font color=\"navajowhite\">dictGetString</font>(<font color=\"lightgreen\">'dns_class'</font>, <font color=\"lightgreen\">'Name'</font>, <font color=\"navajowhite\">toUInt64</font>(Class)), <font color=\"navajowhite\">count</font><font color=\"yellow\">/</font><font color=\"darkcyan\">$interval</font>)) <font color=\"darkorange\">FROM</font> (<font color=\"darkorange\">SELECT</font> <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t, Class, <font color=\"navajowhite\">sum</font>(c) <font color=\"darkorange\">as</font> <font color=\"navajowhite\">count</font> <font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font> <font color=\"darkorange\">WHERE</font> <font color=\"darkcyan\">$timeFilter</font> <font color=\"yellow\">AND</font> Server <font color=\"darkorange\">IN</font>(<font color=\"darkcyan\">$ServerName</font>)   <font color=\"darkorange\">group by</font> t, Class <font color=\"darkorange\">ORDER BY</font> t) <font color=\"darkorange\">group by</font> t<br /> <font color=\"darkorange\">order by</font> t",
     "query": "SELECT t, groupArray((dictGetString('dns_class', 'Name', toUInt64(Class)), count/$interval)) FROM (SELECT $timeSeries as t, Class, sum(c) as count FROM DNS_CLASS WHERE $timeFilter    group by t, Class ORDER BY t) group by t\n order by t",
     "table": "DNS_CLASS",
     "targetLists": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "database": "default",
     "dateColDataType": "DnsDate",
     "dateTimeColDataType": "timestamp",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font> t, <font color=\"navajowhite\">groupArray</font>((<font color=\"navajowhite\">dictGetString</font>(<font color=\"lightgreen\">'dns_response'</font>, <font color=\"lightgreen\">'Name'</font>, <font color=\"navajowhite\">toUInt64</font>(ResponseCode)), <font color=\"navajowhite\">count</font><font color=\"yellow\">/</font><font color=\"darkcyan\">$interval</font>)) <font color=\"darkorange\">FROM</font> (<font color=\"darkorange\">SELECT</font> <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t, ResponseCode, <font color=\"navajowhite\">sum</font>(c) <font color=\"darkorange\">as</font> <font color=\"navajowhite\">count</font> <font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font> <font color=\"darkorange\">WHERE</font> <font color=\"darkcyan\">$timeFilter</font> <font color=\"yellow\">AND</font> Server <font color=\"darkorange\">IN</font>(<font color=\"darkcyan\">$ServerName</font>)   <font color=\"darkorange\">group by</font> t, ResponseCode <font color=\"darkorange\">ORDER BY</font> t) <font color=\"darkorange\">group by</font> t<br /> <font color=\"darkorange\">order by</font> t",
     "query": "SELECT t, groupArray((dictGetString('dns_response', 'Name', toUInt64(ResponseCode)), count/$interval)) FROM (SELECT $timeSeries as t, ResponseCode, sum(c) as count FROM DNS_RESPONSECODE WHERE $timeFilter    group by t, ResponseCode ORDER BY t) group by t\n order by t",
     "table": "DNS_RESPONSECODE",
     "targetLists": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OpCode Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "database": "default",
     "dateColDataType": "DnsDate",
     "dateTimeColDataType": "timestamp",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font> t, <font color=\"navajowhite\">groupArray</font>((<font color=\"navajowhite\">dictGetString</font>(<font color=\"lightgreen\">'dns_opcode'</font>, <font color=\"lightgreen\">'Name'</font>, <font color=\"navajowhite\">toUInt64</font>(OpCode)), <font color=\"navajowhite\">count</font><font color=\"yellow\">/</font><font color=\"darkcyan\">$interval</font>)) <font color=\"darkorange\">FROM</font> (<font color=\"darkorange\">SELECT</font> <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t, OpCode, <font color=\"navajowhite\">sum</font>(c) <font color=\"darkorange\">as</font> <font color=\"navajowhite\">count</font> <font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font> <font color=\"darkorange\">WHERE</font> <font color=\"darkcyan\">$timeFilter</font> <font color=\"yellow\">AND</font> Server <font color=\"darkorange\">IN</font>(<font color=\"darkcyan\">$ServerName</font>)   <font color=\"darkorange\">group by</font> t, OpCode <font color=\"darkorange\">ORDER BY</font> t) <font color=\"darkorange\">group by</font> t<br /> <font color=\"darkorange\">order by</font> t",
     "query": "SELECT t, groupArray((dictGetString('dns_opcode', 'Name', toUInt64(OpCode)), count/$interval)) FROM (SELECT $timeSeries as t, OpCode, sum(c) as count FROM DNS_OPCODE WHERE $timeFilter    group by t, OpCode ORDER BY t) group by t\n order by t",
     "table": "DNS_OPCODE",
     "targetLists": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Edns0 Present in Query",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "database": "default",
     "dateColDataType": "DnsDate",
     "dateTimeColDataType": "timestamp",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font> <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t, sumMerge(EdnsCount)<font color=\"yellow\">/</font><font color=\"darkcyan\">$interval</font> <font color=\"darkorange\">as</font> Edns0Present <font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font> <font color=\"darkorange\">WHERE</font> <font color=\"darkcyan\">$timeFilter</font> <font color=\"yellow\">AND</font> Server <font color=\"darkorange\">IN</font>(<font color=\"darkcyan\">$ServerName</font>)   <font color=\"darkorange\">GROUP BY</font> t <font color=\"darkorange\">ORDER BY</font> t",
     "query": "SELECT $timeSeries as t, sumMerge(EdnsCount)/$interval as Edns0Present FROM DNS_EDNS WHERE $timeFilter    GROUP BY t ORDER BY t",
     "table": "DNS_EDNS",
     "targetLists": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DoBit Present in Packet",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "database": "default",
     "dateColDataType": "DnsDate",
     "dateTimeColDataType": "timestamp",
     "formattedQuery": "<font color=\"darkorange\">SELECT</font> <font color=\"darkcyan\">$timeSeries</font> <font color=\"darkorange\">as</font> t, sumMerge(DoBitCount)<font color=\"yellow\">/</font><font color=\"darkcyan\">$interval</font> <font color=\"darkorange\">as</font> DoBitSet <font color=\"darkorange\">FROM</font> <font color=\"darkcyan\">$table</font> <font color=\"darkorange\">WHERE</font> <font color=\"darkcyan\">$timeFilter</font> <font color=\"yellow\">AND</font> Server <font color=\"darkorange\">IN</font>(<font color=\"darkcyan\">$ServerName</font>)  <font color=\"darkorange\">GROUP BY</font> t <font color=\"darkorange\">ORDER BY</font> t",
     "query": "SELECT $timeSeries as t, sumMerge(DoBitCount)/$interval as DoBitSet FROM DNS_EDNS WHERE $timeFilter   GROUP BY t ORDER BY t",
     "table": "DNS_EDNS",
     "targetLists": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  }
 ]
}